### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by inclyc** [inclyc/lvimdots#1]
- [ ] 优雅的LaTeX展示（长远规划，可能需要嵌一个Electron）
- [ ] LaTeX的snippets。可以直接从vscode中抄，暂时不用太着急
- [ ] Jupyter ascending，这个不错，可以整合jupyter服务器和neovim。
